// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Piwerko.Api.Repo;
using System;

namespace Piwerko.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180414091357_beers")]
    partial class beers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Piwerko.Api.Models.Beer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alcohol");

                    b.Property<int>("breweryId");

                    b.Property<string>("description");

                    b.Property<int>("ibu");

                    b.Property<bool>("isConfirmed");

                    b.Property<string>("name");

                    b.Property<double>("rating");

                    b.Property<int>("servingTemp");

                    b.Property<string>("type");

                    b.HasKey("id");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("Piwerko.Api.Models.Brewery", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("city");

                    b.Property<string>("description");

                    b.Property<bool>("isConfirmed");

                    b.Property<string>("name");

                    b.Property<string>("street");

                    b.Property<int>("streetNumber");

                    b.Property<string>("webUrl");

                    b.HasKey("id");

                    b.ToTable("Breweries");
                });

            modelBuilder.Entity("Piwerko.Api.Models.Rate", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("beerId");

                    b.Property<int>("userId");

                    b.Property<double>("value");

                    b.HasKey("id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Piwerko.Api.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfirmationCode");

                    b.Property<string>("avatar_URL");

                    b.Property<string>("email");

                    b.Property<string>("firstname");

                    b.Property<bool>("isAdmin");

                    b.Property<bool>("isConfirmed");

                    b.Property<string>("lastname");

                    b.Property<string>("password");

                    b.Property<string>("phone");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
